file updates

diff --git a/.dotfiles/snowy/shared/scripts/suspend_timed b/.dotfiles/snowy/shared/scripts/suspend_timed
--- a/.dotfiles/snowy/shared/scripts/suspend_timed
+++ b/.dotfiles/snowy/shared/scripts/suspend_timed
@@ -2,11 +2,13 @@
 
 # This script suspends a systemd-based Linux system after a specified delay.
 
+echo "$@"
+
 # Check if a time argument was provided
-if [ "$#" -ne 1 ]; then
-	echo "$# arguments provided"
-    echo "Usage: ./suspend_timed <time>"
-    exit 1
+if [ $# -lt 1 ]; then
+        echo "$# arguments provided"
+        echo "Usage: ./suspend_timed <time>"
+        exit 1
 fi
 
 # Get the delay time from the first argument
@@ -14,14 +16,14 @@ DELAY="$1"
 
 # Check if the argument is a positive integer
 if ! [[ "$DELAY" =~ ^[0-9]+(s|m|h|d|w)?$ ]]; then
-    echo "Error: Must provide a valid sleep interval."
-    exit 1
+        echo "Error: Must provide a valid sleep interval."
+        exit 1
 fi
 
 if [[ "$DELAY" =~ ^[0-9]+(s|m|h|d|w)$ ]]; then
-   echo "Inhibiting automatic suspend for $DELAY"
+        echo "Inhibiting automatic suspend for $DELAY"
 else
-   echo "Inhibiting automatic suspend for $DELAY seconds..."
+        echo "Inhibiting automatic suspend for $DELAY seconds..."
 fi
 
 echo "Press Ctrl+C to cancel."
@@ -32,12 +34,12 @@ echo "Press Ctrl+C to cancel."
 # && systemctl suspend: This command is only executed if 'systemd-inhibit' exits successfully,
 #                       which happens when the 'sleep' command finishes. This triggers the suspend.
 systemd-inhibit --what=idle:sleep --who="Suspend-script" \
-                --why="Suspending after user-specified delay" sleep "$DELAY" \
-                && systemctl suspend
+        --why="Suspending after user-specified delay" sleep "$DELAY" &&
+        systemctl suspend
 
 # Check the exit status of the combined command
 if [ $? -eq 0 ]; then
-    echo "System suspended successfully."
+        echo "System suspended successfully."
 else
-    echo "The script was interrupted. System might not have been suspended."
+        echo "The script was interrupted. System might not have been suspended."
 fi
